---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    auth-key: AgCcDOdfJtm/VmGbgmWlPSPZvFKjyt238iVQqE4VBqLA4JGxu5EukJo+NQFDfriPRqFCDu9abQR28Y7sdbg+aINK4tr1JEbVppJNMuaper7THaMahMdYcAz6P2XYFFnRrPz+VnTs1JTmY6UA5E6COPQ/dZkRtE1d4jmUe3B2OjuDCw+ZuyXfmFmA4TneDJhIKe+Uhg+eLq+pt4S+ulrmjsPFJeBk/fkvxH9N33j5L6LpoRZra94QT42yiT8kq2V1DJuq8WTcJQYjZN/9+Gd28yAD8sDHIXIAgkiCxQp6t2H4hKr8QEci8ib7AXIFEgU8QKSm3Mm+wEaudwGHL7hzAz/bmkEu2BbQBOiETKCGkWSnbuEjwRuxTits45ffNneIwYaQ0HamIx8PxHQo/mx7TEP9dxM9svatXRhSdauhxS/pqP1D0xJGcSAM4diTLssMQ7wEohqWXKFJrL4OqI9d1flLmyAkXZetTXtBC9iYuJnwhsDg1fVUSB7gKOCL52xh+67eaUKGh8v3s9wl/oZT99/6ZXM6EoMzqSVYgOuNeOd724Tp36IWnddENWTz8H1Dq//jPHo3/OA3x0L5cUcgWRFGWrGhXeIJM5H6m7GMvVxnCRe1W6qNWtH0yKefd1c8LdVSLDD9atzZy/oXVl4f7mE8b0d7JVgcpXnRSJBM/l8y7a7FzFKGnXr3lh1Ef8C/alAL7iPcrn9jtO18AueT3WqTNVZp25aAncJm/dxab8Rsx0D5wex7fpiHdmqQnXT3tPNi0vugROjPesUC6Buf
  template:
    metadata:
      name: tailscale-auth
      namespace: tailscale
    type: Opaque
