apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    auth-key: AgA+JGOz6WY8eMp9UFJhSlJPzEGr3QBrNK2eI2U5tePMmJ2PLqoOkfsjT7w3xNNAgCn2DeO60KByKqheJmuPVmAHK579Fu/9t3Zoad3Cn1rokukzMNF4XKgUx1iYaU9tnawuNEMfRPbWVmmYG5J+0iHBH7HDG5WE1Bkl8GoqyScNU7chGlzYMbiB0B/j5vRTzCwY0TSZCSrB/dDZRw7uHRJ2lOlcyGCpnRX8FoBIxjeZMyzNhZueRKQHUhB2UdZNciAMEWYNnpKpCRrHfZ0If+r+vWO0ADN2gTI6lAX8kjF9sOVmRW3BOK1BeN6lbKwQEK8k8C+KcRADLiq4eqI5HNEiilvuWBjOMdU6GIfHvTBl9p/pRGIJWvNTNEgnruQhHVkzIQa1Bdq1yG9ZuEcBvpjAVoxEcQh7mMxVp1X9xGwoSNvJOtZpPcHEn3LBxXK7lhxZs897qn9Yufn6GJLWpZhUBXPU8kkQZBx528qL5z9/hUgG3a2Y0FrcfBVMNEtnPurxK2U4Y26WMma2Zw0WLnOXaG2mxqrPqkkngpx3L6jn7Ei2u7NYMfT18cXcOoHKscFFzaigdkQ+4rrOEtFCNEshU47ZubLx7eAx/AYZfQWUbY/7zSSMLhr89yxA6jBDLg8iiolKL1PH18cW6v2oN/6bmXd60V3lcUCwVASMq6fHRQDpccEF9xoY8hxX6NI2FPU8aITyk4wPzi/3Y0SdbCGa5eVVQT6tOLw08oDP5xJj7r8uhBh63GsB
  template:
    metadata:
      name: tailscale-auth
      namespace: tailscale
    type: Opaque
