apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    # Note: Let's Encrypt may not work for .ts.net domains
    # Consider using Tailscale's built-in HTTPS certificates instead
    email: your-email@example.com  # TODO: Update with your email or use Tailscale HTTPS
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: traefik

